export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const FETCH_TOKEN = 'FETCH_TOKEN';
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const PLAYER_SCORE = 'PLAYER_SCORE';
export const PLAYER_ASSERTIONS = 'PLAYER_ASSERTIONS';
